### ISSUE TITLE
Cant Find module "toucan-sdk" 

### ISSUE THREAD

**Issue by Victorvikson1996** [ToucanProtocol/toucan-sdk#82]
It seems yarn won't install  `toucan-sdk` on Nextjs when using yarn node package manager

**Comment by GigaHierz** [comment]
Hi @Victorvikson1996 could you tell me which command you are using and what error you are getting? also please provide all infos about your setting, best would be to share the link to the repository you are working on. could you share the code you are working on?

**Comment by Victorvikson1996** [comment]
yarn add toucan-sdk

**Comment by Victorvikson1996** [comment]
> Hi @Victorvikson1996 could you tell me which command you are using and what error you are getting? also please provide all infos about your setting, best would be to share the link to the repository you are working on. could you share the code you are working on?


yarn add toucan-sdk

**Comment by GigaHierz** [comment]
> > Hi @Victorvikson1996 could you tell me which command you are using and what error you are getting? also please provide all infos about your setting, best would be to share the link to the repository you are working on. could you share the code you are working on?
> 
> yarn add toucan-sdk

@Victorvikson1996 could you provide me with a link to your project or an example project with the same setup?

**Comment by Niwilai** [comment]
I cannot replicate this, closing as stale. OP can decide to re-open if necessary.
