### ISSUE TITLE
[Dependency Issue] Isomorphic-unfetch: invalid path for export in package.json

### ISSUE THREAD

**Issue by alinasir85** [ToucanProtocol/toucan-sdk#95]
Hi,

There's an export issue in unfetch version 5 which is mentioned in below PR but its not merged since February 2023

https://github.com/developit/unfetch/pull/164

Toucan-sdk is using "isomorphic-unfetch": "^4.0.2" which internally using unfetch version 5 thus causing below issue while bundling:

**✘ [ERROR] Could not resolve "unfetch"

    ../../../../fireblocks/node_modules/isomorphic-unfetch/index.js:7:14:
      7 │     ? r(require("unfetch"))
        ╵                 ~~~~~~~~~
  The module "./index.js" was not found on the file system:
    ../../../../fireblocks/node_modules/unfetch/package.json:19:17:
      19 │       "default": "./index.js"
         ╵                  ~~~~~~~~~~~~
  You can mark the path "unfetch" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.**

Kindly fix it using alternative library or downgrade **isomorphic-unfetch to 4.0.0** which solves the issue until PR gets merged

**Comment by aspiers** [comment]
Thanks a lot for the report, I have filed an internal ticket to track this.  To clarify, is this breaking installation of the SDK for you, or just certain functionality?  Thanks again!

**Comment by alinasir85** [comment]
Package is not able to build/bundle due to "unfetch" dependency not being resolved in the latest version. 
Had to use version "1.0.0-beta" of toucan-sdk which uses older version of "unfetch" library, hence solving issue

**Comment by pheuberger** [comment]
@alinasir85 which bundler are you using so I can test the behavior?

**Comment by 0xmichalis** [comment]
Fixed by https://github.com/ToucanProtocol/toucan-sdk/pull/104 and published in 1.0.6-beta
